# Ensure CocoaPods installation_root is absolute to avoid Pathname prefix errors
platform :ios, '16.0'

require 'pathname'
Pod::Config.instance.instance_variable_set(:@installation_root, Pathname.new(File.expand_path(__dir__)))

# Load React Native CocoaPods helpers
require_relative '../node_modules/react-native/scripts/react_native_pods.rb'

prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'dahlia' do
  config = use_native_modules!(['node', File.expand_path('rn_config_fixed.js', __dir__)])

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end